import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "./UI/Nav/Nav";
import Footer from "./UI/Footer/Footer";

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={`${font.className}`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
